#[cfg(feature = "telegram")]
pub mod telegram;
#[cfg(feature = "line")]
pub mod line;
#[cfg(feature = "feishu")]
pub mod feishu;
#[cfg(feature = "feishu")]
pub mod feishu_card;
#[cfg(feature = "googlechat")]
pub mod googlechat;
#[cfg(feature = "wecom")]
pub mod wecom;
#[cfg(feature = "teams")]
pub mod teams;
#[cfg(feature = "acp")]
pub mod acp_server;
#[cfg(feature = "acp")]
#[allow(clippy::all, dead_code, unused)]
pub mod acp_schema;
#[cfg(feature = "lineworks")]
pub mod lineworks;
#[cfg(feature = "lineworks")]
pub mod lineworks_flex;
